name: Publish Package to pypi
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: python:latest
    steps:
      - name: Install build dependencies
        run: python3 -m pip install build twine

      - name: Build the package
        run: python3 -m build

      - name: Push artifacts to pypi
        run: python3 -m twine upload 
            --repository pypi 
            --username __token__
            --password ${{ secrets.PYPI_API_KEY }} 
            dist/*